Repository MariaDB/server, pull requests merged in 2021-07, with the labels that each got.

#1873 MDEV-26138: Fix switch case statement in trx_flush_log_if_needed_low()
  storage/innobase/trx/trx0trx.cc
Labels: bug, license-bsd-new

#1870 Fix building crc32_arm64 on NetBSD/aarch64
  mysys/crc32/crc32_arm64.c
Labels: license-bsd-new

#1839 MDEV-24517: JSON_EXTRACT as select conditions syntax error on Spider
  storage/spider/mysql-test/spider/bugfix/include/mdev_24517_deinit.inc
  storage/spider/mysql-test/spider/bugfix/include/mdev_24517_init.inc
  storage/spider/mysql-test/spider/bugfix/r/mdev_24517.result
  storage/spider/mysql-test/spider/bugfix/t/mdev_24517.cnf
  storage/spider/mysql-test/spider/bugfix/t/mdev_24517.test
  storage/spider/spd_db_mysql.cc
Labels: bug

#1879 MDEV-24020: Trim with remove_str Fails on Spider
  storage/spider/mysql-test/spider/bugfix/include/mdev_24020_deinit.inc
  storage/spider/mysql-test/spider/bugfix/include/mdev_24020_init.inc
  storage/spider/mysql-test/spider/bugfix/r/mdev_24020.result
  storage/spider/mysql-test/spider/bugfix/t/mdev_24020.cnf
  storage/spider/mysql-test/spider/bugfix/t/mdev_24020.test
  storage/spider/spd_db_conn.h
  storage/spider/spd_db_mysql.cc
Labels: bug
