Repository MariaDB/server, pull requests merged in 2023-12, with the labels that each got.

#2895 MDEV-32933: Skip statement and mix mode for binlog.flashback
  mysql-test/suite/binlog/t/flashback.test
Labels: MariaDB Corporation

#2900 MDEV-32953: main.rpl_mysqldump_slave Fails with "Master binlog wasn’t…
  mysql-test/main/rpl_mysqldump_slave.result
  mysql-test/main/rpl_mysqldump_slave.test
Labels: MariaDB Corporation

#2744 MDEV-32043 mariadb-upgrade should remove bundled plugins from mysql.plugin
  mysql-test/main/mysql_upgrade.result
  mysql-test/main/mysql_upgrade.test
  scripts/mysql_system_tables_fix.sql
  sql/sql_plugin.cc
Labels: MariaDB Foundation

#2882 MDEV-10653: SHOW SLAVE STATUS Can Deadlock an Errored Slave
  mysql-test/suite/rpl/r/rpl_deadlock_show_slave_status.result
  mysql-test/suite/rpl/t/rpl_deadlock_show_slave_status.test
  sql/rpl_parallel.cc
  sql/rpl_parallel.h
  sql/rpl_rli.h
  sql/slave.cc
Labels: MariaDB Corporation

#2780 MDEV-30482 libmariadb3 - debian/libmariadb3.symbols not updated
  debian/libmariadb3.symbols
Labels: MariaDB Foundation

#2675 MDEV-20286 mariabackup fails when innodb_max_dirty_pages_pct contains…
  extra/mariabackup/xtrabackup.cc
Labels: MariaDB Foundation

#2777 MDEV-21587: disk.disk test result
  plugin/disks/mysql-test/disks/disks.result
  plugin/disks/mysql-test/disks/disks.test
  plugin/disks/mysql-test/disks/disks_notembedded.result
  plugin/disks/mysql-test/disks/disks_notembedded.test
Labels: MariaDB Foundation

#2837 MDEV-32795: ALTER SEQUENCE IF NOT EXISTS non_existing_seq Errors rather than note
  mysql-test/suite/sql_sequence/alter.result
  mysql-test/suite/sql_sequence/alter.test
  sql/sql_base.cc
  sql/sql_yacc.yy
Labels: MariaDB Foundation

#2912 MDEV-32942 Fix Memory Leak in my_print_defaults with Non-Existing Con…
  extra/my_print_defaults.c
Labels: license-mca

#2890 MDEV-32923: drop errmsg-utf8.txt from packaging
  debian/mariadb-server.install
  debian/source/lintian-overrides
  sql/share/CMakeLists.txt
Labels: MariaDB Foundation

#2942 MDEV-33052 MSAN use-of-uninitialized-value in buf_read_ahead_linear()
  storage/innobase/buf/buf0rea.cc
Labels: MariaDB Corporation

#2940 MDEV-31925 mysqld_upgrade --check-if-upgrade-is-needed leaks files
  client/mysql_upgrade.c
  mysql-test/main/mysql_upgrade_file_leak.result
  mysql-test/main/mysql_upgrade_file_leak.test
Labels: license-mca
