Repository MariaDB/server, pull requests merged in 2023-03, with the labels that each got.

#2484 Deb: MariaDB naming
  debian/additions/mariadb.conf.d/50-mariadb-clients.cnf
  debian/additions/mariadb.conf.d/50-mariadb_safe.cnf
  debian/additions/mariadb.conf.d/50-server.cnf
  debian/mariadb-client.install
  debian/mariadb-server.README.Debian
  debian/mariadb-server.install
Labels: MariaDB Foundation

#2507 Fix warning in mariadb-install-db
  scripts/mysql_install_db.sh
Labels: MariaDB Foundation

#2505 MDEV-30697, MDEV-30698 - raw [and] flashback options for mariadb-binlog test coverage and memory leak
  client/mysqlbinlog.cc
  mysql-test/suite/binlog/r/binlog_mysqlbinlog_raw_flush.result
  mysql-test/suite/binlog/r/flashback.result
  mysql-test/suite/binlog/t/binlog_mysqlbinlog_raw_flush.test
  mysql-test/suite/binlog/t/flashback.test
Labels: MariaDB Foundation

#2489 MDEV-30613 output_core_info crashes in my_read()
  sql/signal_handler.cc
Labels: MariaDB Foundation

#2532 MDEV-30810 errmsg-utf8.txt no longer uses charsets
  extra/comp_err.c
  sql/derror.cc
  sql/share/errmsg-utf8.txt
Labels: MariaDB Foundation

#2565 sql_class: sprintf -> snprintf
  sql/sql_class.h
Labels: MariaDB Foundation

#2566 rpl_reporting: sprintf -> snprintf
  sql/rpl_reporting.h
Labels: MariaDB Foundation

#2558 [MDEV-19629] Backport FORMAT_PICO_TIME from MySQL to MariaDB
  libmysqld/CMakeLists.txt
  mysql-test/suite/perfschema/r/pfs_functions.result
  mysql-test/suite/perfschema/t/pfs_functions.test
  sql/CMakeLists.txt
  sql/item.h
  sql/item_create.cc
  sql/item_pfsfunc.cc
  sql/item_pfsfunc.h
Labels: license-mca

#2386 MDEV-30276 - wsrep_sst_mariabackup to use mariadb-backup
  scripts/wsrep_sst_mariabackup.sh
Labels: MariaDB Foundation

#2569 CODING_STANDARDS: Add variable initializations and functions spacing
  CODING_STANDARDS.md
Labels: license-mca

#2540 [MDEV-30543] New status variable: max_used_connections_time
  mysql-test/main/status.result
  mysql-test/main/status.test
  sql/mysqld.cc
Labels: license-bsd-new

#2585 Revert "Added mysql-log-rotate to .gitignore"
  .gitignore
Labels: MariaDB Foundation
