Repository MariaDB/server, pull requests merged in 2023-04, with the labels that each got.

#2547 Handle meaningless addr2line results and increase timeout
  mysys/my_addr_resolve.c
Labels: license-bsd-new

#2501 MDEV-30502: Change lsb-base to sysvinit-utils
  debian/autobake-deb.sh
  debian/control
Labels: MariaDB Foundation

#2586 fix typo
  sql/log.cc
  sql/log_event.h
Labels: license-mca

#2392 MDEV-30205 Move /usr/share/mysql to /usr/share/mariadb
  .gitignore
  .gitlab-ci.yml
  client/mysql_upgrade.c
  cmake/create_initial_db.cmake
  cmake/install_layout.cmake
  debian/additions/debian-start
  debian/additions/mariadb.conf.d/60-galera.cnf
  debian/mariadb-plugin-mroonga.install
  debian/mariadb-plugin-mroonga.prerm
  debian/mariadb-server-core.install
  debian/mariadb-server.install
  debian/mariadb-server.postinst
  debian/mariadb-test-data.install
  debian/mariadb-test-data.lintian-overrides
  debian/mariadb-test.install
  debian/mariadb-test.links
  debian/mariadb-test.lintian-overrides
  debian/not-installed
  debian/rules
  debian/salsa-ci.yml
  debian/source/lintian-overrides
  debian/tests/upstream
  man/mariadbd-multi.1
  mysql-test/README
  mysql-test/README.stress
  mysql-test/lib/mtr_cases.pm
  mysql-test/mariadb-test-run.pl
  scripts/CMakeLists.txt
  scripts/mariadb_performance_tables.sql
  scripts/mariadb_system_tables.sql
  scripts/mariadb_system_tables_data.sql
  scripts/mariadb_system_tables_fix.sql
  scripts/mariadb_test_data_timezone.sql
  scripts/mariadb_test_db.sql
  scripts/mysql_install_db.sh
  scripts/sys_schema/CMakeLists.txt
  sql/CMakeLists.txt
  sql/privilege.h
  support-files/policy/apparmor/usr.sbin.mysqld
  support-files/rpm/server-postin.sh
  support-files/rpm/server.cnf
Labels: MariaDB Foundation

#2592 MDEV-30205: /usr/share/mysql-test -> mariadb-test (fix)
  mysql-test/suite/encryption/r/innodb-bad-key-change.result
  mysql-test/suite/encryption/t/innodb-bad-key-change.test
Labels: MariaDB Foundation

#2567 my alloca fixes
  include/my_alloca.h
Labels: MariaDB Foundation

#2502 MDEV-30687: Make small facelifting to autobake-debs.sh
  debian/autobake-deb.sh
Labels: MariaDB Foundation

#2605 MDEV-27009: Add UCA-14.0.0 collations - License
  THIRDPARTY
Labels: MariaDB Foundation

#2611 MDEV-30186 unintialized value where there are no test cases
  mysql-test/mariadb-test-run.pl
Labels: MariaDB Foundation

#2508 MDEV-30713 field length handling for CONNECT engine
  storage/connect/catalog.h
  storage/connect/ha_connect.cc
  storage/connect/tabext.cpp
  storage/connect/value.cpp
  storage/connect/value.h
Labels: MariaDB Foundation

#2610 MDEV-31038: Parallel Replication Breaks if XA PREPARE Fails Updating Slave GTID State
  mysql-test/suite/rpl/r/rpl_xa_prepare_gtid_fail.result
  mysql-test/suite/rpl/t/rpl_xa_prepare_gtid_fail.test
  sql/handler.cc
  sql/log_event.h
  sql/log_event_server.cc
Labels: MariaDB Corporation
