Repository MariaDB/server, pull requests merged in 2024-04, with the labels that each got.

#3162 MDEV-33787 : Fix Galera test failures on 10.11
  mysql-test/suite/galera/r/MDEV-25731.result
  mysql-test/suite/galera/r/galera_wan_restart_sst.result
  mysql-test/suite/galera/t/MDEV-25731.test
  mysql-test/suite/galera/t/galera_ist_mariabackup_verify_ca.cnf
  mysql-test/suite/galera/t/galera_wan_restart_sst.test
  mysql-test/suite/galera/t/rpl_galera_to_mariadb_clone_slave_using_mariadb-backup.cnf
  mysql-test/suite/galera_3nodes/r/galera_allowlist.result
  mysql-test/suite/galera_3nodes/t/galera_allowlist.test
  mysql-test/suite/galera_3nodes_sr/r/GCF-832.result
  mysql-test/suite/galera_3nodes_sr/r/galera_sr_kill_slave_before_apply.result
  mysql-test/suite/galera_3nodes_sr/t/GCF-832.test
  mysql-test/suite/galera_3nodes_sr/t/galera_sr_kill_slave_before_apply.test
Labels: Codership

#3168 MDEV-33799: mysql_manager_submit Segfault at Startup Still Possible During Recovery
  mysql-test/suite/rpl/r/rpl_mysql_manager_race_condition.result
  mysql-test/suite/rpl/t/rpl_mysql_manager_race_condition.test
  sql/mysqld.cc
Labels: MariaDB Corporation

#3140 MDEV-21102: Server crashes in JOIN_CACHE::write_record_data upon EXPL…
  mysql-test/main/join_cache.result
  mysql-test/main/join_cache.test
  sql/item_subselect.cc
  sql/sql_join_cache.cc
  sql/sql_select.cc
Labels: bug, MariaDB Corporation

#3128 MDEV-33672: Gtid_log_event Construction from File Should Ensure Event Length When Using Extra Flags
  mysql-test/suite/rpl/r/rpl_gtid_header_valid.result
  mysql-test/suite/rpl/t/rpl_gtid_header_valid.test
  sql/log_event.cc
  sql/log_event.h
  sql/log_event_server.cc
Labels: MariaDB Corporation

#3122 MDEV-32974 : Member fails to join due to old seqno in GTID
  mysql-test/suite/galera/r/galera_sst_mariabackup,debug.rdiff
  mysql-test/suite/galera/r/galera_sst_mariabackup.result
  mysql-test/suite/galera/t/galera_sst_mariabackup.cnf
  mysql-test/suite/galera/t/galera_sst_mariabackup.test
  storage/innobase/trx/trx0rseg.cc
Labels: Codership

#3101 MDEV-33592: Use X509v3 for compatibility with libraries
  vio/viosslfactories.c
Labels: MariaDB Foundation

#3200 MDEV-33895 : Galera test failure on galera_sr.MDEV-25718
  mysql-test/suite/galera_sr/t/MDEV-25718.test
Labels: Codership

#3040 MDEV-12404 Index condition pushdown on partitioned tables
  mysql-test/main/ignored_index.result
  mysql-test/main/partition_icp.result
  mysql-test/main/partition_icp.test
  mysql-test/main/partition_mrr_aria.result
  mysql-test/main/partition_mrr_innodb.result
  mysql-test/main/partition_mrr_myisam.result
  mysql-test/main/partition_pruning.result
  sql/ha_partition.cc
  sql/ha_partition.h
  storage/example/ha_example.cc
  storage/rocksdb/mysql-test/rocksdb/r/rocksdb_cf_per_partition.result
Labels: enhancement, MariaDB Corporation

#3191 MDEV-27512: Assertion !thd->transaction_rollback_request failed in rows_event_stmt_cleanup
  mysql-test/suite/rpl/r/rpl_skip_error.result
  mysql-test/suite/rpl/r/rpl_temporary_error2_skip_all.result
  mysql-test/suite/rpl/t/rpl_skip_error.test
  mysql-test/suite/rpl/t/rpl_temporary_error2.test
  mysql-test/suite/rpl/t/rpl_temporary_error2_skip_all-slave.opt
  mysql-test/suite/rpl/t/rpl_temporary_error2_skip_all.test
  sql/log_event_server.cc
Labels: MariaDB Corporation

#3074 MDEV-33492: mysql_install_db fails when baseurl is set
  scripts/mysql_install_db.sh
Labels: MariaDB Foundation

#3142 MDEV-33574 Improve mysqlbinlog error message
  client/mysqlbinlog.cc
Labels: license-bsd-new

#3116 MDEV-33631 Ubuntu/Debian MYSQL_SERVER_SUFFIX is version+suffix on Mar…
  debian/rules
Labels: MariaDB Foundation
