Repository MariaDB/server, pull requests merged in 2024-02, with the labels that each got.

#2941 Update my_print_defaults man page with mariadbd option
  man/my_print_defaults.1
Labels: MariaDB Foundation

#2760 MDEV-31768: Alias MASTER_DEMOTE_TO_REPLICA for MASTER_DEMOTE_TO_SLAVE
  mysql-test/suite/rpl/r/rpl_change_master_demote.result
  mysql-test/suite/rpl/t/rpl_change_master_demote.test
  sql/lex.h
Labels: MariaDB Corporation

#2104 MDEV-28419 subsequent runs of debian/autobake-deb.sh are not idempotent
  debian/autobake-deb.sh
Labels: MariaDB Foundation

#2861 MDEV-24507: Server Crash using UDF in WHERE clause of VIEW
  mysql-test/main/udf.result
  mysql-test/main/udf.test
  sql/item_func.cc
  sql/sql_udf.h
Labels: license-bsd-new

#3024 MDEV-33301 memlock with systemd still not working
  cmake/cpack_rpm.cmake
  debian/mariadb-server-core-10.5.postinst
  support-files/policy/apparmor/usr.sbin.mysqld
  support-files/policy/selinux/mariadb-server.te
Labels: MariaDB Foundation
