Repository MariaDB/server, pull requests merged in 2024-11, with the labels that each got.

#3603 MDEV-35301: Bump minimum cmake version to 3.12.0
  CMakeLists.txt
Labels: MariaDB Foundation

#3612 MDEV-35350: Consolidate MTR wait_for_pattern_in_file.inc and SEARCH_WAIT in search_pattern_in_file.inc
  mysql-test/include/search_pattern_in_file.inc
  mysql-test/include/wait_for_pattern_in_file.inc
  mysql-test/suite/rpl/r/rpl_binlog_dump_slave_gtid_state_info.result
  mysql-test/suite/rpl/r/rpl_semi_sync_shutdown_await_ack.result
  mysql-test/suite/rpl/t/rpl_binlog_dump_slave_gtid_state_info.test
  mysql-test/suite/rpl/t/rpl_semi_sync_shutdown_await_ack.inc
  mysql-test/suite/rpl/t/rpl_semi_sync_shutdown_await_ack.test
Labels: MariaDB Corporation

#3606 MDEV-35115 Inconsistent Replace behaviour when multiple unique index exist
  mysql-test/suite/innodb/r/innodb-replace,INPLACE.rdiff
  mysql-test/suite/innodb/r/innodb-replace.result
  mysql-test/suite/innodb/t/innodb-replace.combinations
  mysql-test/suite/innodb/t/innodb-replace.test
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/handler/ha_innodb.h
Labels: MariaDB Corporation

#3485 Extract some of #3360 fixes to 10.5.x
  client/mysqldump.c
  plugin/server_audit/server_audit.c
  sql/item_cmpfunc.cc
  sql/item_geofunc.cc
  sql/item_strfunc.cc
  sql/log_event_server.cc
  sql/my_decimal.cc
  sql/slave.cc
  sql/sql_acl.cc
  sql/sql_class.h
  sql/sql_trigger.cc
  sql/sql_type.h
  sql/sql_yacc.yy
  sql/table.cc
  sql/wsrep_var.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/trx/trx0undo.cc
  storage/maria/s3_func.c
  storage/mroonga/lib/mrn_multiple_column_key_codec.cpp
  storage/myisam/ha_myisam.cc
  storage/myisam/mi_check.c
  storage/myisam/myisamchk.c
  storage/oqgraph/ha_oqgraph.cc
  storage/spider/spd_db_mysql.cc
Labels: MariaDB Corporation, GSoC

#3638 Create FUNDING.yml
  .github/FUNDING.yml
Labels: MariaDB Corporation

#3636 MDEV-35394 Innochecksum misinterprets freed undo pages
  extra/innochecksum.cc
  mysql-test/suite/innodb/r/innochecksum_undo_page.result
  mysql-test/suite/innodb/t/innochecksum_undo_page.opt
  mysql-test/suite/innodb/t/innochecksum_undo_page.test
  mysql-test/suite/innodb_zip/r/innochecksum_2.result
  mysql-test/suite/innodb_zip/r/innochecksum_3.result
Labels: MariaDB Corporation

#3469 MDEV-33075 [backport/2f5174e556] [10.5] Resolve server shutdown issues on macOS, Solaris, and FreeBSD
  sql/mysqld.cc
Labels: External Contribution

#3667 MDEV-35513 fails to compile on RISC-V 32
  include/my_rdtsc.h
Labels: MariaDB Foundation

#3668 MDEV-35508 Race condition between purge and secondary index INSERT or UPDATE
  mysql-test/suite/innodb/r/purge_pessimistic.result
  mysql-test/suite/innodb/t/purge_pessimistic.opt
  mysql-test/suite/innodb/t/purge_pessimistic.test
  storage/innobase/btr/btr0cur.cc
  storage/innobase/include/trx0sys.h
  storage/innobase/include/trx0trx.h
  storage/innobase/include/ut0pool.h
  storage/innobase/row/row0purge.cc
  storage/innobase/trx/trx0sys.cc
Labels: MariaDB Corporation
