Repository MariaDB/server, pull requests merged in 2024-10, with the labels that each got.

#2556 [MDEV-14978] Client programs to use $MARIADB_HOST consistently
  client/mysql.cc
  client/mysqladmin.cc
  client/mysqlbinlog.cc
  client/mysqlcheck.c
  client/mysqldump.cc
  client/mysqlimport.cc
  client/mysqlshow.c
  client/mysqlslap.c
  mysql-test/suite/client/client-env-variable.cnf
  mysql-test/suite/client/client-env-variable.result
  mysql-test/suite/client/client-env-variable.test
Labels: license-bsd-new, need feedback

#3544 MDEV-34122: Assertion entry failed in Active_tranx::assert_thd_is_waiter
  mysql-test/suite/rpl/r/rpl_semi_sync_cond_var_per_thd.result
  mysql-test/suite/rpl/t/rpl_semi_sync_cond_var_per_thd.test
  sql/semisync_master.cc
  sql/semisync_master.h
  sql/sql_class.cc
  sql/sql_class.h
Labels: MariaDB Corporation

#3599 MDEV-35265 wsrep.wsrep-recover, wsrep.wsrep-recover-v25 fail on assertion
  sql/handler.cc
  storage/innobase/handler/ha_innodb.cc
Labels: Codership

#3443 MDEV-34665 Simplify IN predicate processing for NULL-aware materializ…
  mysql-test/main/subselect_mat.result
  mysql-test/main/subselect_mat.test
  mysql-test/main/subselect_mat_analyze_json.result
  mysql-test/main/subselect_mat_analyze_json.test
  sql/item_subselect.cc
  sql/item_subselect.h
Labels: MariaDB Corporation
