Repository MariaDB/server, pull requests merged in 2024-07, with the labels that each got.

#3350 MDEV-34437 restrict port number to valid values
  mysql-test/suite/sys_vars/r/sysvars_server_embedded.result
  mysql-test/suite/sys_vars/r/sysvars_server_notembedded.result
  sql/sys_vars.cc
Labels: MariaDB Foundation

#3352 MDEV-34437: handle error on getaddrinfo
  mysql-test/main/bad_startup_options_debug.result
  mysql-test/main/bad_startup_options_debug.test
  sql/mysqld.cc
Labels: MariaDB Foundation

#3378 MDEV-34502 InnoDB debug mode build - asserts with Valgrind
  storage/innobase/include/mach0data.inl
Labels: MariaDB Foundation

#3099 MDEV-33465: an option to enable semisync recovery
  mysql-test/suite/binlog/r/binlog_truncate_active_log.result
  mysql-test/suite/binlog/r/binlog_truncate_multi_engine.result
  mysql-test/suite/binlog/r/binlog_truncate_multi_log.result
  mysql-test/suite/binlog/t/binlog_truncate_active_log.inc
  mysql-test/suite/binlog/t/binlog_truncate_active_log.test
  mysql-test/suite/binlog/t/binlog_truncate_multi_engine.test
  mysql-test/suite/binlog/t/binlog_truncate_multi_log.test
  mysql-test/suite/binlog/t/binlog_truncate_multi_log_unsafe.test
  mysql-test/suite/rpl/r/rpl_semi_sync_fail_over.result
  mysql-test/suite/rpl/t/rpl_semi_sync_crash.inc
  sql/log.cc
  sql/mysqld.cc
Labels: MariaDB Corporation

#3323 MDEV-32892: IO Thread Reports False Error When Stopped During Connect…
  mysql-test/suite/rpl/r/rpl_stop_slave_error.result
  mysql-test/suite/rpl/t/rpl_stop_slave_error.test
  sql/slave.cc
Labels: MariaDB Corporation

#3385 MDEV-34528: bundle fmt version 11.0.0
  cmake/libfmt.cmake
  cmake/os/Windows.cmake
Labels: MariaDB Foundation

#3349 MDEV-33921: Replication fails when XA transactions are used where the slave has replicate_do_db...
  client/mysqlbinlog.cc
  mysql-test/suite/rpl/r/rpl_xa_empty_transaction.result
  mysql-test/suite/rpl/t/rpl_xa_empty_transaction.test
  sql/handler.cc
  sql/log_event.h
  sql/log_event_client.cc
  sql/log_event_server.cc
  sql/rpl_filter.cc
  sql/rpl_filter.h
  sql/xa.cc
  sql/xa.h
Labels: MariaDB Corporation

#3383 MDEV-34490 get_copy() and build_clone() may return an instance of an …
  plugin/func_test/plugin.cc
  plugin/type_inet/item_inetfunc.h
  plugin/type_inet/sql_type_inet.cc
  sql/item.cc
  sql/item.h
  sql/item_cmpfunc.cc
  sql/item_cmpfunc.h
  sql/item_func.h
  sql/item_geofunc.h
  sql/item_jsonfunc.h
  sql/item_row.cc
  sql/item_row.h
  sql/item_strfunc.h
  sql/item_subselect.h
  sql/item_sum.h
  sql/item_timefunc.h
  sql/item_vers.h
  sql/item_windowfunc.h
  sql/item_xmlfunc.cc
  sql/item_xmlfunc.h
  sql/procedure.h
  sql/sql_list.h
  sql/sql_select.cc
  sql/sql_string.h
Labels: MariaDB Corporation

#2997 Small cleanup of replication code (log.cc)
  sql/log.cc
Labels: MariaDB Foundation

#3387 MDEV-34099: AddressSanitizer running out of memory regardless of stack_thread size
  sql/sql_parse.cc
Labels: MariaDB Foundation

#3167 MDEV-33010 Condition with CHARSET()/COERCIBILITY() erroneously pushed…
  mysql-test/main/derived_cond_pushdown_innodb.result
  mysql-test/main/derived_cond_pushdown_innodb.test
  mysql-test/main/olap.result
  mysql-test/main/olap.test
  sql/item_func.cc
  sql/item_func.h
  sql/item_strfunc.cc
  sql/item_strfunc.h
Labels: bug, MariaDB Corporation

#3237 MDEV-33988 DELETE single table to support table aliases
  mysql-test/main/delete.result
  mysql-test/main/delete.test
  mysql-test/main/delete_use_source.result
  mysql-test/main/delete_use_source.test
  mysql-test/main/partition_explicit_prune.result
  mysql-test/main/partition_explicit_prune.test
  mysql-test/main/trigger-compat.result
  sql/sql_yacc.yy
Labels: MariaDB Foundation

#3415 MDEV-34634 Types mismatch when cloning items causes debug assertion
  mysql-test/main/item_types.result
  mysql-test/main/item_types.test
  sql/item.cc
  sql/item.h
  sql/sql_select.cc
Labels: bug, MariaDB Corporation
