Repository MariaDB/server, pull requests merged in 2025-10, with the labels that each got.

#4325 MDEV-35951 : Complete freeze during MW-329 test
  mysql-test/suite/galera/disabled.def
  mysql-test/suite/galera/r/MW-329.result
  mysql-test/suite/galera/t/MW-329.test
Labels: Codership

#4330 MDEV-37774: ASAN crash in Gap_time_tracker's log_time()
  sql/sql_class.cc
Labels: MariaDB Corporation

#4341 MDEV-37209 : mtr galera_3nodes.galera_garbd_backup test failures
  mysql-test/suite/galera_3nodes/r/galera_garbd_backup.result
  mysql-test/suite/galera_3nodes/t/galera_garbd_backup.test
Labels: Codership

#4339 MDEV-37797 - main.information_schema_db fails sporadically
  mysql-test/main/information_schema_db.result
  mysql-test/main/information_schema_db.test
Labels: MariaDB Foundation

#4346 MDEV-36556: MariaDB restart after upgrade fails with innodb_encrypt_tables
  mysql-test/suite/encryption/r/recovery_memory.result
  mysql-test/suite/encryption/t/recovery_memory.combinations
  mysql-test/suite/encryption/t/recovery_memory.test
  storage/innobase/ibuf/ibuf0ibuf.cc
Labels: MariaDB Corporation
