Repository MariaDB/server, pull requests merged in 2025-01, with the labels that each got.

#3725 MDEV-34119 Assertion `page_dir_get_n_heap(new_page) == 2U' failed in dberr_t PageBulk::init()
  mysql-test/suite/innodb/r/insert_into_empty,4k.rdiff
  mysql-test/suite/innodb/r/insert_into_empty,8k.rdiff
  mysql-test/suite/innodb/r/insert_into_empty.result
  mysql-test/suite/innodb/t/insert_into_empty.test
  storage/innobase/row/row0ins.cc
Labels: MariaDB Corporation

#3730 MDEV-35773 ER_PSEUDO_THREAD_ID_OVERWRITE in 11.4 shifts error messages
  mysql-test/suite/rpl/r/rpl_xa.result
  mysql-test/suite/rpl/r/rpl_xa_gtid_pos_auto_engine.result
  sql/share/errmsg-utf8.txt
Labels: MariaDB Corporation

#3691 MDEV-34898 Doublewrite recovery of innodb_checksum_algorithm=full_crc32 encrypted pages does not work
  extra/mariabackup/xtrabackup.cc
  mysql-test/suite/encryption/r/debug_key_management.result
  mysql-test/suite/encryption/r/doublewrite_debug.result
  mysql-test/suite/encryption/t/debug_key_management.test
  mysql-test/suite/encryption/t/doublewrite_debug.opt
  mysql-test/suite/encryption/t/doublewrite_debug.test
  storage/innobase/buf/buf0buf.cc
  storage/innobase/buf/buf0dblwr.cc
  storage/innobase/include/log0recv.h
  storage/innobase/log/log0recv.cc
  storage/innobase/srv/srv0start.cc
Labels: MariaDB Corporation

#3734 MDEV-35647 Possible hang during CREATE TABLE…SELECT error handling
  mysql-test/suite/innodb/r/create_select.result
  mysql-test/suite/innodb/t/create_select.test
  storage/innobase/handler/ha_innodb.cc
Labels: MariaDB Corporation

#3704 MDEV-35568 Reintroduce delete_while_scanning for multi_delete
  mysql-test/main/myisam_explain_non_select_all.result
  mysql-test/suite/innodb/r/innodb.result
  mysql-test/suite/innodb/r/innodb_mysql.result
  mysql-test/suite/perfschema/r/multi_table_io.result
  sql/sql_class.h
  sql/sql_delete.cc
Labels: MariaDB Corporation

#3640 MDEV-35438 Annotate InnoDB I/O functions with noexcept
  storage/innobase/btr/btr0sea.cc
  storage/innobase/buf/buf0buf.cc
  storage/innobase/buf/buf0dblwr.cc
  storage/innobase/buf/buf0flu.cc
  storage/innobase/buf/buf0rea.cc
  storage/innobase/fil/fil0crypt.cc
  storage/innobase/fil/fil0fil.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/include/buf0buf.h
  storage/innobase/include/buf0dblwr.h
  storage/innobase/include/buf0flu.h
  storage/innobase/include/buf0rea.h
  storage/innobase/include/buf0types.h
  storage/innobase/include/fil0fil.h
  storage/innobase/include/os0file.h
  storage/innobase/log/log0recv.cc
  storage/innobase/mtr/mtr0mtr.cc
  storage/innobase/os/os0file.cc
Labels: MariaDB Corporation

#3744 Fix -DBUILD_CONFIG=mysql_release to keep standard cmake flags
  cmake/build_configurations/mysql_release.cmake
  storage/innobase/include/trx0trx.h
Labels: MariaDB Foundation

#3738 MDEV-35554 call to function show_binlog_space_total()
  sql/mysqld.cc
Labels: MariaDB Foundation

#3747 MDEV-35431: fix InnoDB flags error size specifier
  storage/innobase/fsp/fsp0file.cc
Labels: MariaDB Corporation

#3670 MDEV-35528: mariadb-binlog cannot process more than 1 logfiles when --stop-datetime is specified
  client/mysqlbinlog.cc
  mysql-test/suite/binlog/r/binlog_mysqlbinlog_warn_stop_datetime.result
  mysql-test/suite/binlog/r/binlog_mysqlbinlog_warn_stop_position.result
  mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_datetime.inc
  mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_datetime.test
  mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_position.inc
  mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_position.test
Labels: license-bsd-new, External Contribution

#3750 MDEV-35687 Various UBSAN function-type-mismatch debug_sync and myisam
  include/mysql/plugin.h
  include/mysql/service_debug_sync.h
Labels: MariaDB Foundation

#3746 MDEV-35818: Fix `replace_binlog_file` info message
  sql/log.cc
Labels: MariaDB Corporation

#3748 MDEV-35430: Add cast to semi-sync wait skip msg
  sql/semisync_master.cc
Labels: MariaDB Corporation

#3741 MDEV-35805 Update main.lowercase_table4 for new default collation
  mysql-test/main/lowercase_table4.result
Labels: MariaDB Corporation

#3756 MDEV-35096: History is stored in different partitions on different nodes when using SYSTEM VERSION
  mysql-test/suite/rpl/r/rpl_system_versioning_partitions.result
  mysql-test/suite/rpl/t/rpl_system_versioning_partitions.cnf
  mysql-test/suite/rpl/t/rpl_system_versioning_partitions.test
  sql/sql_lex.h
Labels: MariaDB Corporation

#3760 MDEV-35838 libressl support differences in CRYPTO_set_mem_functions
  mysys_ssl/openssl.c
Labels: MariaDB Foundation

#3749 more MDEV-35429 my_snprintf fixes for 10.5+
  storage/innobase/os/os0file.cc
  storage/myisam/mi_check.c
Labels: MariaDB Corporation

#3751 MDEV-34703 LOAD DATA INFILE using Innodb bulk load aborts
  mysql-test/suite/innodb/r/bulk_load.result
  mysql-test/suite/innodb/t/bulk_load.opt
  mysql-test/suite/innodb/t/bulk_load.test
  sql/sql_load.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/include/row0merge.h
  storage/innobase/include/trx0trx.h
  storage/innobase/row/row0ins.cc
  storage/innobase/row/row0merge.cc
  storage/innobase/trx/trx0rec.cc
Labels: MariaDB Corporation

#3758 MDEV-35837 Move to c++17
  CMakeLists.txt
  cmake/cpack_rpm.cmake
  plugin/handler_socket/handlersocket/database.cpp
  plugin/handler_socket/handlersocket/database.hpp
  plugin/handler_socket/handlersocket/handlersocket.cpp
  plugin/handler_socket/handlersocket/hstcpsvr.cpp
  plugin/handler_socket/handlersocket/hstcpsvr.hpp
  plugin/handler_socket/handlersocket/hstcpsvr_worker.cpp
  plugin/handler_socket/handlersocket/hstcpsvr_worker.hpp
  plugin/handler_socket/libhsclient/hstcpcli.hpp
  storage/mroonga/CMakeLists.txt
  storage/mroonga/vendor/groonga/CMakeLists.txt
  storage/mroonga/vendor/groonga/vendor/plugins/groonga-normalizer-mysql/CMakeLists.txt
Labels: MariaDB Corporation

#3721 MDEV-35646: Limit `pseudo_thread_id` to `UINT32_MAX`
  include/my_pthread.h
  mysql-test/suite/sys_vars/r/sysvars_server_embedded.result
  mysql-test/suite/sys_vars/r/sysvars_server_notembedded.result
  sql/mysqld.cc
  sql/sys_vars.cc
Labels: MariaDB Corporation

#3706 MDEV-35338 - Non-copying ALTER does not pad VECTOR column, vector sea…
  mysql-test/main/vector_innodb.result
  mysql-test/main/vector_innodb.test
  storage/innobase/handler/ha_innodb.cc
Labels: MariaDB Corporation

#3774 MDEV-34703 followup - reenable Innodb bulk load in mariadb-import
  client/mysqlimport.cc
Labels: MariaDB Corporation

#3715 MDEV-35102 CREATE TABLE AS SELECT ST_collect ... does not work
  mysql-test/main/spatial_utility_function_collect.result
  mysql-test/main/spatial_utility_function_collect.test
  sql/item_sum.cc
  sql/item_sum.h
Labels: MariaDB Corporation

#3776 MDEV-35445 Disable foreign key column nullability check for strict sql mode
  mysql-test/suite/innodb/r/foreign_sql_mode,COPY,NON-STRICT.rdiff
  mysql-test/suite/innodb/r/foreign_sql_mode,COPY,NOSTRICT.rdiff
  mysql-test/suite/innodb/r/foreign_sql_mode,INPLACE,NON-STRICT.rdiff
  mysql-test/suite/innodb/r/foreign_sql_mode.result
  mysql-test/suite/innodb/t/foreign_sql_mode.combinations
  mysql-test/suite/innodb/t/foreign_sql_mode.test
  sql/sql_table.cc
  storage/innobase/dict/dict0crea.cc
  storage/innobase/handler/handler0alter.cc
Labels: MariaDB Corporation

#3717 MDEV-35665 Potential Buffer Overrun in Gtid_log_event::write()
  sql/log_event_server.cc
Labels: MariaDB Corporation

#3623 MDEV-33285 - Assertion `m_table' failed in ha_perfschema::rnd_end on CHECKSUM TABLE
  mysql-test/main/kill_debug.result
  mysql-test/main/kill_debug.test
  sql/handler.cc
  sql/sql_table.cc
Labels: MariaDB Corporation

#3789 MDEV-35921: s3.mysqldump fails in buildbot
  mysql-test/suite/s3/mysqldump.result
Labels: MariaDB Foundation

#3745 MDEV-35806: Error in read_log_event() corrupts relay log writer, cras…
  client/mysqlbinlog.cc
  mysql-test/suite/rpl/r/rpl_from_mysql80.result
  mysql-test/suite/rpl/t/rpl_from_mysql80.test
  mysys/mf_iocache.c
  sql/log.cc
  sql/log_event.cc
  sql/log_event.h
  sql/log_event_server.cc
  sql/rpl_parallel.cc
  sql/rpl_rli.cc
  sql/slave.cc
  sql/sql_repl.cc
Labels: MariaDB Foundation

#3794 MDEV-35964 fix cast warnings on mac in mysql_file.h
  include/mysql/psi/mysql_file.h
Labels: MariaDB Corporation

#3784 MDEV-35169 ALTER TABLE...IMPORT TABLESPACE does not work with INDEX DESC
  mysql-test/suite/innodb/r/import_cfg.result
  mysql-test/suite/innodb/r/innodb-wl5522-debug.result
  mysql-test/suite/innodb/t/import_cfg.test
  mysql-test/suite/innodb/t/innodb-wl5522-debug.test
  storage/innobase/row/row0import.cc
  storage/innobase/row/row0quiesce.cc
Labels: MariaDB Corporation

#3391 MDEV-26652: xa transactions binlogged in wrong order
  mysql-test/suite/rpl/r/rpl_xa_2pc_multi_engine.result
  mysql-test/suite/rpl/t/rpl_xa_2pc_multi_engine.test
Labels: MariaDB Corporation
