Repository MariaDB/server, pull requests merged in 2025-09, with the labels that each got.

#4276 MDEV-37553: Assertion failure lsn - get_flushed_lsn(std::memory_order_relaxed) < capacity()
  storage/innobase/mtr/mtr0mtr.cc
Labels: MariaDB Corporation

#4278 SQL parser: add -fno-strict-aliasing to gcc<9 aarch build
  sql/CMakeLists.txt
Labels: MariaDB Foundation

#4289 MDEV-30692: conf_to_src incompatible with CHARSET_INFO changes (postfix)
  strings/conf_to_src.c
Labels: MariaDB Foundation

#4291 MDEV-37548 : wsrep_allowlist allows all connections during SST
  sql/wsrep_allowlist_service.cc
Labels: Codership

#4288 MDEV-37412 Corrupted page during recovery aborts the server
  mysql-test/suite/innodb/r/leaf_page_corrupted_during_recovery.result
  mysql-test/suite/innodb/t/leaf_page_corrupted_during_recovery.test
  storage/innobase/log/log0recv.cc
Labels: MariaDB Corporation

#4292 MDEV-37619 The forced use of THD accessors hurts InnoDB performance
  sql/sql_class.cc
  storage/innobase/dict/dict0crea.cc
  storage/innobase/dict/dict0dict.cc
  storage/innobase/eval/eval0eval.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/handler/ha_innodb.h
  storage/innobase/handler/handler0alter.cc
  storage/innobase/include/eval0eval.inl
  storage/innobase/include/ha_prototypes.h
  storage/innobase/include/trx0i_s.h
  storage/innobase/include/trx0trx.h
  storage/innobase/lock/lock0lock.cc
  storage/innobase/row/row0ins.cc
  storage/innobase/row/row0sel.cc
  storage/innobase/row/row0uins.cc
  storage/innobase/trx/trx0i_s.cc
  storage/innobase/trx/trx0purge.cc
  storage/innobase/trx/trx0trx.cc
  storage/rocksdb/ha_rocksdb.cc
Labels: MariaDB Corporation

#4238 MDEV-37434 Fix broken query_id field in server_audit plugin (10.11)
  mysql-test/suite/plugins/r/server_audit_query_id.result
  mysql-test/suite/plugins/t/normalize_query_id.pl
  mysql-test/suite/plugins/t/server_audit_query_id.opt
  mysql-test/suite/plugins/t/server_audit_query_id.test
  plugin/server_audit/server_audit.c
  sql/sp_head.cc
  sql/sql_audit.h
  sql/sql_parse.cc
Labels: External Contribution

#4298 MDEV-37299: Fix server crash when encryption is ON and server is read-only
  mysql-test/suite/encryption/r/innodb-read-only.result
  mysql-test/suite/encryption/t/innodb-read-only.test
  storage/innobase/fil/fil0crypt.cc
Labels: MariaDB Corporation

#4088 MDEV-35163 InnoDB persistent statistics fail to update after ALTER TABLE...ALGORITHM=COPY
  mysql-test/suite/innodb/r/alter_copy_stats.result
  mysql-test/suite/innodb/r/innodb-alter-debug.result
  mysql-test/suite/innodb/r/xap_release_locks_on_dict_stats_table.result
  mysql-test/suite/innodb/t/alter_copy_stats.test
  mysql-test/suite/innodb/t/innodb-alter-debug.test
  mysql-test/suite/innodb/t/xap_release_locks_on_dict_stats_table.test
  mysql-test/suite/innodb_fts/t/versioning.test
  storage/innobase/dict/dict0stats.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/handler/ha_innodb.h
  storage/innobase/handler/handler0alter.cc
Labels: MariaDB Corporation

#4320 MDEV-37724: Memory leak with InnoDB ALTER TABLE ALGORITHM=INSTANT
  storage/innobase/handler/handler0alter.cc
Labels: MariaDB Foundation

#4188 MDEV-36190: Optimize transaction_lock_guard use
  storage/innobase/btr/btr0btr.cc
  storage/innobase/btr/btr0cur.cc
  storage/innobase/btr/btr0pcur.cc
  storage/innobase/buf/buf0buf.cc
  storage/innobase/buf/buf0lru.cc
  storage/innobase/buf/buf0rea.cc
  storage/innobase/dict/dict0dict.cc
  storage/innobase/include/buf0buf.h
  storage/innobase/include/trx0purge.h
  storage/innobase/lock/lock0lock.cc
  storage/innobase/trx/trx0purge.cc
  storage/innobase/trx/trx0rec.cc
Labels: MariaDB Corporation

#4315 10.11-MDEV-31744: frame_range_n_bottom assertion error
  mysql-test/main/win.result
  mysql-test/main/win.test
  mysql-test/suite/encryption/r/tempfiles_encrypted.result
  sql/sql_window.cc
Labels: MariaDB Corporation

#4308 MDEV-37680/MDEV-24941: RHEL9+,Centos-stream and Fedora to pull mysql-selinux-1.0.14+ dependency
  cmake/cpack_rpm.cmake
Labels: MariaDB Foundation
