Repository MariaDB/server, pull requests merged in 2025-06, with the labels that each got.

#4085 MDEV-34863 RAM Usage Changed Significantly Between 10.11 Releases (po…
  storage/innobase/buf/buf0buf.cc
Labels: MariaDB Foundation

#4056 Replace deprecated CMAKE_COMPILER_IS_GNU(CC|CXX) with CMAKE_(C|CXX)_COMPILER_ID
  CMakeLists.txt
  cmake/build_configurations/mysql_release.cmake
  cmake/dtrace.cmake
  cmake/maintainer.cmake
  cmake/os/SunOS.cmake
  mysys/CMakeLists.txt
  scripts/CMakeLists.txt
  storage/innobase/CMakeLists.txt
  storage/mroonga/CMakeLists.txt
Labels: External Contribution

#4082 MDEV-24588: Assertion `item->name.str && item->name.str[0]` failed in `TABLE_LIST::create_field_translation` on SELECT
  mysql-test/main/derived.result
  mysql-test/main/derived.test
  sql/table.cc
Labels: MariaDB Corporation

#4059 Rocksdb: Add missing getauxval() test for Linux
  cmake/os/WindowsCache.cmake
  storage/rocksdb/CMakeLists.txt
Labels: External Contribution

#4040 MDEV-37001 Enable building RocksDB on non-Linux aarch64 OSes
  storage/rocksdb/CMakeLists.txt
  storage/rocksdb/build_rocksdb.cmake
Labels: External Contribution

#4032 MDEV-35837: Update CODING_STANDARDS to C++17
  CODING_STANDARDS.md
Labels: MariaDB Corporation

#4091 MDEV-29300 Assertion `*ref && (*ref)->fixed()' failed in Item_field:…
  mysql-test/main/subselect4.result
  mysql-test/main/subselect4.test
  sql/item.cc
Labels: MariaDB Corporation

#4101 MDEV-30363 InnoDB: Failing assertion: trx->error_state == DB_SUCCESS in que_run_threads
  mysql-test/suite/innodb_fts/r/innodb_fts_misc_1.result
  mysql-test/suite/innodb_fts/t/innodb_fts_misc_1.test
  storage/innobase/handler/ha_innodb.cc
Labels: MariaDB Corporation

#4072 MDEV-34425 mroonga files are not copied by mariabackup
  extra/mariabackup/backup_copy.cc
  extra/mariabackup/backup_copy.h
  mysql-test/suite/mariabackup/mroonga.opt
  mysql-test/suite/mariabackup/mroonga.result
  mysql-test/suite/mariabackup/mroonga.test
Labels: External Contribution

#4119 MDEV-36962 innodb.log_file_overwrite fails with ASAN errors
  storage/innobase/buf/buf0buf.cc
Labels: MariaDB Corporation

#4120 MDEV-37019 MSAN_STAT_WORKAROUND macro remove
  extra/mariabackup/fil_cur.cc
  extra/mariabackup/xtrabackup.cc
  include/my_valgrind.h
  mysys/my_lib.c
  mysys/my_symlink.c
  sql/datadict.cc
  sql/discover.cc
  sql/parse_file.cc
  storage/innobase/log/log0log.cc
  storage/innobase/os/os0file.cc
  storage/myisam/mi_info.c
Labels: MariaDB Foundation

#3870 MDEV-36106 New-style hints: [NO_]DERIVED_CONDITION_PUSHDOWN, [NO_]MERGE
  mysql-test/main/opt_hints_derived_condition_pushdown.result
  mysql-test/main/opt_hints_derived_condition_pushdown.test
  mysql-test/main/opt_hints_merge.result
  mysql-test/main/opt_hints_merge.test
  sql/opt_hints.cc
  sql/opt_hints.h
  sql/opt_hints_parser.cc
  sql/opt_hints_parser.h
  sql/sql_select.cc
  sql/table.cc
Labels: MariaDB Corporation

#4123 MDEV-36650 Unexpected checkpoint in the test innodb.doublewrite
  mysql-test/suite/innodb/t/doublewrite.test
Labels: MariaDB Corporation

#4121 MDEV-36215 Fix Wrong query result due to Table Elimination
  mysql-test/main/table_elim.result
  mysql-test/main/table_elim.test
  sql/opt_table_elimination.cc
Labels: MariaDB Corporation

#4136 MDEV-37049 my_assume_aligned assertion in mariabackup
  extra/mariabackup/xtrabackup.cc
Labels: MariaDB Corporation

#4127 MDEV-37033 UBSAN: row_log_table_apply_ops runtime error: applying non-zero offset 1048576 to null pointer
  storage/innobase/row/row0log.cc
Labels: MariaDB Foundation

#4138 MDEV-35863 innodb.doublewrite_debug test case fails to start the server
  mysql-test/suite/innodb/r/doublewrite_debug.result
  mysql-test/suite/innodb/t/doublewrite_debug.test
  storage/innobase/srv/srv0start.cc
Labels: MariaDB Corporation

#4141 MDEV-36697: Wrong server.cnf group for version
  support-files/rpm/server.cnf
Labels: MariaDB Foundation

#4122 MDEV-36959 Deadlock does not rollback transaction fully
  mysql-test/suite/innodb/r/trx_deadlock.result
  mysql-test/suite/innodb/t/trx_deadlock.opt
  mysql-test/suite/innodb/t/trx_deadlock.test
  sql/transaction.cc
Labels: MariaDB Corporation

#4144 MDEV-36738: mariadb@.service incorrectly changing pam ownership in mariadb-install-db
  support-files/MacOSX/ReadMe.txt
  support-files/MacOSX/postflight.sh
  support-files/binary-configure.sh
  support-files/mariadb.service.in
  support-files/mariadb@.service.in
Labels: MariaDB Foundation
