Repository MariaDB/server, pull requests merged in 2025-02, with the labels that each got.

#3809 MDEV-34489 innodb.innodb_row_lock_time_ms fails
  mysql-test/suite/innodb/r/innodb_row_lock_time_ms.result
  mysql-test/suite/innodb/t/innodb_row_lock_time_ms.test
Labels: MariaDB Corporation

#3716 MDEV-35117 Improve error message on unexpected geometries for st_dist…
  mysql-test/main/gis-precise.result
  mysql-test/main/gis-precise.test
  mysql-test/main/gis.result
  mysql-test/main/gis.test
  sql/item_geofunc.cc
Labels: MariaDB Corporation

#3825 Update mariadb-import man page with --innodb-optimize-keys option
  man/mariadb-import.1
Labels: MariaDB Foundation

#3815 MDEV-36015: unrepresentable value in row_parse_int()
  mysql-test/suite/innodb/r/autoinc_persist.result
  mysql-test/suite/innodb/t/autoinc_persist.test
  storage/innobase/include/row0row.h
  storage/innobase/include/row0row.inl
  storage/innobase/include/row0sel.h
  storage/innobase/row/row0ins.cc
  storage/innobase/row/row0sel.cc
Labels: MariaDB Corporation

#3834 MDEV-35436 dict_stats_fetch_from_ps() unnecessarily holds exclusive dict_sys.latch
  storage/innobase/dict/dict0stats.cc
  storage/innobase/pars/pars0pars.cc
Labels: MariaDB Corporation

#3805 MDEV-35975 Server crashes after CREATE VIEW as SELECT ST_COLLECT...
  mysql-test/main/spatial_utility_function_collect.result
  mysql-test/main/spatial_utility_function_collect.test
  sql/item_sum.cc
Labels: MariaDB Corporation

#3821 MDEV-36038 ALTER TABLE…SEQUENCE does not work correctly with InnoDB
  mysql-test/suite/sql_sequence/alter.opt
  mysql-test/suite/sql_sequence/alter.result
  mysql-test/suite/sql_sequence/alter.test
  sql/ha_sequence.cc
  sql/ha_sequence.h
  sql/sql_table.cc
  storage/innobase/handler/handler0alter.cc
Labels: MariaDB Corporation

#3835 MDEV-36082 Race condition between log_t::resize_start() and log_t::resize_abort()
  storage/innobase/buf/buf0flu.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/include/log0log.h
  storage/innobase/log/log0log.cc
Labels: MariaDB Corporation

#3844 MDEV-36124 Fix missing binary failures from test_upgrade.sh
  tests/upgrade_from/test_upgrade.sh
Labels: External Contribution

#3841 MDEV-27126 my_getopt compares option names case sensitively
  mysql-test/main/my_getopt_case_insensitive.opt
  mysql-test/main/my_getopt_case_insensitive.result
  mysql-test/main/my_getopt_case_insensitive.test
  mysql-test/suite/wsrep/r/wsrep_mixed_case_cmd_arg.result
  mysql-test/suite/wsrep/t/wsrep_mixed_case_cmd_arg.cnf
  mysql-test/suite/wsrep/t/wsrep_mixed_case_cmd_arg.opt
  mysql-test/suite/wsrep/t/wsrep_mixed_case_cmd_arg.test
  mysys/my_getopt.c
Labels: External Contribution

#3852 MDEV-36152 mariadb-backup --backup crash during innodb_undo_log_truncate=ON, innodb_encrypt_log=ON
  storage/innobase/log/log0recv.cc
Labels: MariaDB Corporation

#3858 MDEV-36155: MSAN use-of-uninitialized-value innodb.log_file_size_online
  storage/innobase/log/log0log.cc
Labels: MariaDB Foundation

#3860 MDEV-36156: MSAN Compile and Link flags needed for compile/run checks
  CMakeLists.txt
Labels: MariaDB Foundation
