Repository MariaDB/server, pull requests merged in 2025-04, with the labels that each got.

#3940 MDEV-36469 don't check is_infoschema_db for null db
  sql/lex_ident.h
  sql/sql_parse.cc
Labels: MariaDB Foundation

#3916 MDEV-36236 Instant alter aborts when InnoDB fails to rollback instant operation correctly
  mysql-test/suite/innodb/r/instant_alter_debug,redundant.rdiff
  mysql-test/suite/innodb/r/instant_alter_debug.result
  mysql-test/suite/innodb/t/instant_alter_debug.test
  storage/innobase/handler/handler0alter.cc
Labels: MariaDB Corporation

#3948 MDEV-36480 USAN: checking identifier names for 0 length names
  sql/sql_parse.cc
Labels: MariaDB Foundation

#3951 MDEV-36427 - FTBFS with libxml2 2.14.0
  storage/connect/plgxml.h
  storage/connect/tabxml.cpp
Labels: MariaDB Foundation

#3818 MDEV-35721 UBSAN: runtime error: -nan outside range
  mysql-test/main/mdev-35721-ubsan.result
  mysql-test/main/mdev-35721-ubsan.test
  sql/sql_statistics.cc
Labels: MariaDB Corporation

#3699 MDEV-35640 Protocol_text: handle errors in allocation
  sql/protocol.cc
  sql/protocol.h
  sql/sql_prepare.cc
Labels: MariaDB Foundation

#3666 MDEV-35512 remove all RPM compat packages
  cmake/cpack_rpm.cmake
Labels: MariaDB Foundation

#3850 MDEV-36184 - To optimise dot_product in Power9 and Power10 architecture
  sql/bloom_filters.h
  sql/vector_mhnsw.cc
Labels: External Contribution

#3847 MDEV-33671 Remove hardcoded open-files limit in safe_process.cc
  mysql-test/lib/My/SafeProcess.pm
  mysql-test/lib/My/SafeProcess/safe_process.cc
  mysql-test/mariadb-test-run.pl
Labels: External Contribution

#3982 MDEV-36613 Incorrect undo logging for indexes on virtual columns
  mysql-test/suite/gcol/r/innodb_virtual_basic.result
  mysql-test/suite/gcol/t/innodb_virtual_basic.test
  storage/innobase/trx/trx0rec.cc
Labels: MariaDB Corporation

#3953 MDEV-36238 11.4 follow-up: `Master_SSL_Verify_Server_Cert=0`
  mysql-test/suite/multi_source/master_info_file.result
  mysql-test/suite/multi_source/master_info_file.test
Labels: MariaDB Corporation, Replication

#3971 MDEV-36504 Memory leak after CREATE TABLE..SELECT
  include/my_base.h
  mysql-test/suite/innodb/r/alter_copy_bulk.result
  mysql-test/suite/innodb/t/alter_copy_bulk.test
  sql/ha_partition.cc
  sql/sql_insert.cc
  sql/sql_table.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/handler/handler0alter.cc
  storage/innobase/include/trx0trx.h
  storage/innobase/include/trx0types.h
  storage/innobase/row/row0ins.cc
  storage/innobase/row/row0mysql.cc
  storage/innobase/trx/trx0trx.cc
  storage/mroonga/ha_mroonga.cpp
Labels: MariaDB Corporation

#3957 MDEV-36211 Incorrect result for BLOB type with NOT NULL constraint
  mysql-test/main/func_like.result
  mysql-test/main/func_like.test
  sql/item.h
  sql/item_cmpfunc.h
Labels: MariaDB Corporation

#3981 MDEV-36463 Rename expression_cache to subquery_cache
  mysql-test/main/analyze_format_json.result
  mysql-test/main/explain_json.result
  mysql-test/main/order_by.result
  mysql-test/main/show_analyze_json.result
  mysql-test/main/show_explain_json.result
  mysql-test/main/subselect4.result
  mysql-test/main/subselect_cache.result
  sql/sql_explain.cc
Labels: MariaDB Corporation

#3980 MDEV-36607 find_order_in_list mismatch when order item needs fixing()
  sql/sql_select.cc
Labels: MariaDB Corporation

#3931 MDEV-36359: Patch NULL deref after disabling semi-sync primary
  mysql-test/suite/rpl/r/rpl_semi_sync_master_disable_with_slave.result
  mysql-test/suite/rpl/t/rpl_semi_sync_master_disable_with_slave.test
  sql/semisync_master.cc
Labels: MariaDB Corporation, Replication

#3964 MDEV-36235 Incorrect result for BETWEEN over unique blob prefix
  mysql-test/main/type_binary.result
  mysql-test/main/type_binary.test
  mysql-test/main/type_blob.result
  mysql-test/main/type_blob.test
  mysql-test/main/type_varbinary.result
  mysql-test/main/type_varbinary.test
  plugin/type_inet/mysql-test/type_inet/type_inet6.result
  plugin/type_inet/mysql-test/type_inet/type_inet6.test
  sql/item_cmpfunc.h
  sql/opt_range.cc
Labels: MariaDB Corporation

#3475 MDEV-35999 - Update THIRDPARTY license file to reflect reality
  THIRDPARTY
Labels: External Contribution

#3963 Fix typos in user-facing messages
  extra/mariabackup/xtrabackup.cc
  man/mysql-test-run.pl.1
  mysql-test/lib/v1/mtr_cases.pl
  mysql-test/lib/v1/mtr_io.pl
  mysql-test/lib/v1/mysql-test-run.pl
  mysql-test/main/mysqld--help.result
  mysql-test/mariadb-test-run.pl
  mysql-test/suite/engines/README
  mysql-test/suite/engines/rr_trx/run_stress_tx_rr.pl
  scripts/mysql_setpermission.sh
  scripts/mytop.sh
  scripts/wsrep_sst_common.sh
  sql-bench/copy-db.sh
  sql-bench/crash-me.sh
  sql-bench/server-cfg.sh
  sql-bench/test-connect.sh
  sql/mysqld.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/ut/ut0ut.cc
  storage/mroonga/vendor/groonga/lib/nfkc.rb
Labels: External Contribution

#3829 MDEV-11341 STR_TO_DATE does not return NULL for invalid dates
  mysql-test/main/func_time.result
  mysql-test/main/func_time.test
  mysql-test/main/strict.result
  mysql-test/main/strict.test
  sql/item_timefunc.cc
Labels: External Contribution

#3840 MDEV-14091 Support password protected SSL key in server.
  include/violite.h
  mysql-test/lib/encrypted-server-key-password.txt
  mysql-test/lib/generate-ssl-certs.sh
  mysql-test/main/bad_startup_options.result
  mysql-test/main/bad_startup_options.test
  mysql-test/main/ssl_encrypted_key-master.opt
  mysql-test/main/ssl_encrypted_key.cnf
  mysql-test/main/ssl_encrypted_key.combinations
  mysql-test/main/ssl_encrypted_key.result
  mysql-test/main/ssl_encrypted_key.test
  mysql-test/main/variables.result
  mysql-test/std_data/encrypted-server-key-password.txt
  mysql-test/std_data/encrypted-server-key.pem
  mysql-test/suite/sys_vars/r/sysvars_server_embedded.result
  mysql-test/suite/sys_vars/r/sysvars_server_notembedded.result
  sql/mysqld.cc
  sql/mysqld.h
  sql/sys_vars.cc
  vio/viosslfactories.c
Labels: MariaDB Corporation

#1800 MDEV-23538: Rename mariadb.pc to mariadb-embedded-server.pc to avoid confusion
  debian/libmariadb-dev.install
  debian/libmariadbd-dev.install
  debian/rules
Labels: External Contribution

#3897 MDEV-35304 fixup: Timing-independent MTR test
  mysql-test/suite/multi_source/connects_tried.result
  mysql-test/suite/multi_source/connects_tried.test
Labels: MariaDB Corporation, Replication

#3989 MDEV-36649 dict_acquire_mdl_shared() aborts when table mode is DICT_TABLE_OP_OPEN_ONLY_IF_CACHED
  mysql-test/suite/innodb/r/stats_persistent.result
  mysql-test/suite/innodb/t/stats_persistent.test
  storage/innobase/dict/dict0dict.cc
Labels: MariaDB Corporation

#3977 MDEV-36592: In JOIN ... USING(columns), query plan depends on join order
  mysql-test/main/join.result
  mysql-test/main/join.test
  sql/sql_base.cc
Labels: MariaDB Corporation

#3848 MDEV-31134: sync galera settings with KB doc
  debian/additions/mariadb.conf.d/60-galera.cnf
Labels: MariaDB Foundation

#3990 MDEV-36304 InnoDB: Missing FILE_CREATE, FILE_DELETE or FILE_MODIFY error during mariabackup --prepare
  storage/innobase/log/log0recv.cc
Labels: MariaDB Corporation

#3974 MDEV-36340: Reset `Connects_Tried` with `Master_Retry_Count=X`
  mysql-test/suite/multi_source/connects_tried.result
  mysql-test/suite/multi_source/connects_tried.test
  sql/sql_repl.cc
Labels: MariaDB Corporation, Replication

#3811 MDEV-27669: Add `skip-slave-start` info message
  mysql-test/main/skip_slave_start.result
  mysql-test/main/skip_slave_start.test
  sql/slave.cc
Labels: MariaDB Corporation

#3996 MDEV-36639 innodb_snapshot_isolation=1 gives error for not committed …
  mysql-test/suite/innodb/r/lock_isolation.result
  mysql-test/suite/innodb/t/lock_isolation.test
  storage/innobase/lock/lock0lock.cc
Labels: MariaDB Corporation

#3958 MDEV-36398 Extend SBOM with 'license' and 'copyright'
  cmake/3rdparty_info.cmake
  cmake/generate_sbom.cmake
  cmake/sbom.json.in
Labels: MariaDB Corporation

#4003 MDEV-36663 Semi-sync Replica Can't Kill Dump Thread When Using SSL
  mysql-test/suite/rpl/r/rpl_semi_sync_ssl_stop.result
  mysql-test/suite/rpl/t/rpl_semi_sync_ssl_stop.test
  sql/rpl_mi.cc
  sql/rpl_mi.h
  sql/semisync_slave.cc
  sql/semisync_slave.h
  sql/slave.cc
Labels: MariaDB Corporation, Replication

#4004 packaging prep for Ubuntu Plucky
  debian/autobake-deb.sh
Labels: MariaDB Foundation

#4007 MDEV-36682 Conflict between MDEV-36504 and MDEV-16329
  storage/innobase/handler/ha_innodb.cc
Labels: MariaDB Corporation

#4008 MDEV-36648 - main.mdl_sync extra test.t2 row in I_S.metadata_lock_info
  mysql-test/main/mdl_sync.result
  mysql-test/main/mdl_sync.test
Labels: MariaDB Foundation

#3863 MDEV-14432: mysqldump does not preserve case of table names in generated sql
  mysql-test/main/lowercase_table2.result
  sql/sql_show.cc
Labels: External Contribution

#4013 MDEV-36666 - atomic.alter_table still times out often
  mysql-test/suite/atomic/README.txt
  mysql-test/suite/atomic/alter_table.inc
  mysql-test/suite/atomic/alter_table_aria.test
  mysql-test/suite/atomic/alter_table_innodb.opt
  mysql-test/suite/atomic/alter_table_innodb.result
  mysql-test/suite/atomic/alter_table_innodb.test
  mysql-test/suite/atomic/alter_table_myisam.result
  mysql-test/suite/atomic/alter_table_myisam.test
  mysql-test/suite/atomic/alter_table_rocksdb.test
  mysql-test/suite/atomic/alter_table_trigger.test
Labels: MariaDB Foundation

#3872 MDEV-32732 Support DESC indexes in loose scan optimization
  mysql-test/main/desc_index_range.result
  mysql-test/main/desc_index_range.test
  mysql-test/main/myisam.result
  mysql-test/suite/maria/maria2.result
  sql/opt_range.cc
  sql/opt_range.h
Labels: MariaDB Corporation

#4015 MDEV-36694 spatial_utility_function{_collect,_isvalid} broken for --view-protocol
  mysql-test/main/spatial_utility_function_collect.result
  mysql-test/main/spatial_utility_function_collect.test
  mysql-test/main/spatial_utility_function_isvalid.result
  mysql-test/main/spatial_utility_function_isvalid.test
Labels: MariaDB Corporation

#3853 MDEV-35837: Update CODING_STANDARDS to C++17
  CODING_STANDARDS.md
Labels: MariaDB Corporation

#3938 Add clarifying comment for field parsing in TABLE_SHARE::init_from_binary_frm_image
  sql/table.cc
Labels: External Contribution

#4025 MDEV-36168 ASAN error in Item_func_latlongfromgeohash::decode_geohash…
  sql/item_geofunc.cc
Labels: MariaDB Foundation

#4009 MDEV-36684 - main.mdl_sync fails under valgrind (test for Bug#42643)
  sql/sql_base.cc
  sql/sql_class.h
  sql/table_cache.cc
  storage/innobase/trx/trx0purge.cc
Labels: MariaDB Foundation
