Repository MariaDB/server, pull requests merged in 2025-03, with the labels that each got.

#3854 Rewrite the 'Types' chapter in coding standards.
  CODING_STANDARDS.md
Labels: MariaDB Corporation

#3843 MDEV-23818 mysql option --script-dir
  client/mysql.cc
  mysql-test/main/client.result
  mysql-test/main/client.test
Labels: External Contribution

#3884 MDEV-36253 Redundant check in wf_incremental_process()
  extra/mariabackup/backup_mysql.cc
  extra/mariabackup/write_filt.cc
  extra/mariabackup/xtrabackup.cc
Labels: MariaDB Corporation

#3866 MDEV-30000: Force an InnoDB checkpoint in mariadb-backup
  extra/mariabackup/xtrabackup.cc
  mysql-test/suite/encryption/t/doublewrite_debug.test
  mysql-test/suite/mariabackup/full_backup.result
  mysql-test/suite/mariabackup/full_backup.test
  mysql-test/suite/mariabackup/partial.result
  mysql-test/suite/mariabackup/partial_exclude.result
  mysql-test/suite/mariabackup/unsupported_redo.result
  mysql-test/suite/sys_vars/r/sysvars_innodb.result
  storage/innobase/handler/ha_innodb.cc
Labels: MariaDB Corporation

#3611 MDEV-36009 - Systemd: Restart on OOM
  support-files/mariadb.service.in
  support-files/mariadb@.service.in
Labels: External Contribution

#3857 MDEV-36149 UBSAN in X is outside the range of representable values of…
  mysql-test/suite/sys_vars/r/sysvars_innodb,32bit.rdiff
  mysql-test/suite/sys_vars/r/sysvars_innodb.result
  storage/innobase/buf/buf0flu.cc
  storage/innobase/handler/ha_innodb.cc
  storage/innobase/include/srv0srv.h
Labels: MariaDB Corporation

#3875 MDEV-36238 Functional Tests for --master-info-file and --show-slave-auth-info
  mysql-test/suite/multi_source/master_info_file.opt
  mysql-test/suite/multi_source/master_info_file.result
  mysql-test/suite/multi_source/master_info_file.test
  mysql-test/suite/multi_source/show_slave_auth_info.cnf
  mysql-test/suite/multi_source/show_slave_auth_info.result
  mysql-test/suite/multi_source/show_slave_auth_info.test
Labels: MariaDB Corporation

#3905 MDBF-1000: implement an export for the server repository
  .github/workflows/backup.yml
Labels: MariaDB Foundation

#3892 MDEV-34621: Fix division by zero in mariadb-slap when iterations=0
  client/mysqlslap.c
  mysql-test/main/mysqlslap.result
  mysql-test/main/mysqlslap.test
Labels: External Contribution

#3887 MDEV-35420 Server aborts while deleting the record in spatial index
  mysql-test/suite/innodb_gis/r/rollback.result
  mysql-test/suite/innodb_gis/t/rollback.test
  storage/innobase/gis/gis0sea.cc
Labels: MariaDB Corporation

#3910 MDBF-1000: wrong urls
  .github/workflows/backup.yml
Labels: MariaDB Foundation

#3871 MDEV-36217: Fix building with Clang and GCC on RISC-V
  include/my_cpu.h
Labels: External Contribution

#3787 MDEV-21375: Get option group suffix from $MARIADB_GROUP_SUFFIX in addition to $MYSQL_GROUP_SUFFIX
  mysys/my_default.c
Labels: External Contribution

#3914 Add a sanity check for backups
  .github/workflows/backup.yml
Labels: MariaDB Foundation

#3920 MDEV-36373 Bogus Warning: ... storage is corrupted
  mysql-test/suite/innodb/r/stat_tables.result
  mysql-test/suite/innodb/t/stat_tables.test
  storage/innobase/handler/ha_innodb.cc
Labels: MariaDB Corporation

#3890 MDEV-36270 mariabackup.incremental_compressed fails in 10.11+
  extra/mariabackup/xtrabackup.cc
  mysql-test/suite/mariabackup/incremental_compressed.result
  mysql-test/suite/mariabackup/incremental_compressed.test
Labels: MariaDB Corporation

#3922 MDEV-36381: Comment "Procedure of keys generation ..." is in the wron…
  sql/sql_select.cc
  sql/table.cc
Labels: MariaDB Corporation

#3873 MDEV-36229: Remove CAP_DAC_OVERRIDE CAP_AUDIT_WRITE from AmbientCapabilities
  support-files/mariadb.service.in
  support-files/mariadb@.service.in
Labels: MariaDB Foundation

#3904 MDEV-24035 fixup: GCC 4.8.5 CMAKE_BUILD_TYPE=Debug
  storage/innobase/trx/trx0trx.cc
Labels: MariaDB Corporation

#3896 MDEV-36180 Doublewrite recovery of innodb_checksum_algorithm=full_crc32 page_compressed pages does not work
  mysql-test/suite/encryption/r/doublewrite_debug.result
  mysql-test/suite/encryption/t/doublewrite_debug.opt
  mysql-test/suite/encryption/t/doublewrite_debug.test
  storage/innobase/buf/buf0buf.cc
  storage/innobase/buf/buf0dblwr.cc
  storage/innobase/include/log0recv.h
  storage/innobase/log/log0recv.cc
Labels: MariaDB Corporation

#3894 MDEV-36281 DML aborts during online virtual index
  mysql-test/suite/innodb/r/innodb-index-online.result
  mysql-test/suite/innodb/t/innodb-index-online.test
  storage/innobase/row/row0log.cc
Labels: MariaDB Corporation

#3917 MDEV-32084: Assertion in best_extension_by_limited_search() ...
  mysql-test/main/join_nested.result
  mysql-test/main/join_nested.test
  mysql-test/main/join_nested_jcl6.result
  sql/sql_select.cc
Labels: MariaDB Corporation

#3928 MDEV-36168 ASAN error in Item_func_latlongfromgeohash::decode_geohash
  mysql-test/main/spatial_utility_function_geohash.result
  mysql-test/main/spatial_utility_function_geohash.test
  sql/item_geofunc.cc
  sql/item_geofunc.h
Labels: MariaDB Corporation

#3898 MDEV-36042 Assertion failed in Binary_string::q_append
  mysql-test/main/spatial_utility_function_isvalid.result
  mysql-test/main/spatial_utility_function_isvalid.test
  sql/spatial.cc
Labels: MariaDB Corporation

#3930 MDEV-34158 st_geohash error reporting and null handling
  mysql-test/main/spatial_utility_function_geohash.result
  mysql-test/main/spatial_utility_function_geohash.test
  sql/item_geofunc.cc
Labels: MariaDB Corporation

#3933 MDEV-36420 Assertion failure in SET GLOBAL innodb_ft_aux_table
  mysql-test/suite/innodb_fts/r/innodb_ft_aux_table.result
  mysql-test/suite/innodb_fts/t/innodb_ft_aux_table.test
  storage/innobase/handler/ha_innodb.cc
Labels: MariaDB Corporation

#3885 MDEV-36226 Stall and crash when page cleaner fails to generate free p…
  mysql-test/mariadb-test-run.pl
  storage/innobase/buf/buf0dblwr.cc
  storage/innobase/buf/buf0flu.cc
  storage/innobase/dict/dict0dict.cc
  storage/innobase/include/buf0buf.h
  storage/innobase/include/buf0dblwr.h
  storage/innobase/include/os0file.h
  storage/innobase/os/os0file.cc
  storage/innobase/srv/srv0srv.cc
Labels: MariaDB Corporation
