Repository MariaDB/server, pull requests merged in 2025-08, with the labels that each got.

#4222 MDEV-37192 Crash recovery after bulk load data reports corruption
  mysql-test/suite/innodb/r/bulk_load.result
  mysql-test/suite/innodb/t/bulk_load.test
  storage/innobase/row/row0ins.cc
Labels: MariaDB Corporation

#4079 Make sure the 'lex_hash.h' and 'lex_token.h' header files are packed
  sql/CMakeLists.txt
Labels: External Contribution

#4231 MDEV-37360: SIGSEGV in srv_printf_innodb_monitor
  storage/innobase/srv/srv0srv.cc
Labels: MariaDB Corporation

#4221 MDEV-37296 ALTER TABLE allows adding unique hash key with duplicate values
  mysql-test/suite/innodb/r/alter_copy_bulk.result
  mysql-test/suite/innodb/t/alter_copy_bulk.test
  storage/innobase/include/dict0mem.h
  storage/innobase/row/row0ins.cc
Labels: MariaDB Corporation

#4245 MDEV-36159 mariabackup failed after upgrade
  extra/mariabackup/backup_mysql.cc
  extra/mariabackup/xtrabackup.cc
  mysql-test/suite/mariabackup/full_backup.test
  mysql-test/suite/mariabackup/partial.test
  mysql-test/suite/mariabackup/partial_exclude.test
  mysql-test/suite/mariabackup/unsupported_redo.test
Labels: MariaDB Corporation

#4250 MDEV-37411: Clear warnings for io_setup failure
  mysql-test/mariadb-test-run.pl
  tpool/aio_libaio.cc
Labels: MariaDB Foundation

#4246 MDEV-29981: Replica stops with "Found invalid event in binary log"
  mysql-test/suite/rpl/r/rpl_heartbeat_at_rotate.result
  mysql-test/suite/rpl/t/rpl_heartbeat_at_rotate.test
  sql/log.cc
  sql/slave.cc
Labels: MariaDB Corporation, Replication

#4260 MDEV-37438: UBSAN add_ext_keyuse_for_splitting downcast Item_func_equal -> Item_func_eq
  sql/opt_split.cc
Labels: MariaDB Foundation

#4044 MDEV-32294 fix_fields() problem with inconsistent outer context paths
  mysql-test/main/subquery_merge.result
  mysql-test/main/subquery_merge.test
  sql/sql_lex.cc
Labels: MariaDB Corporation

#4272 MDEV-33817/MDEV-37170 fixup: Remove evex512
  mysys/crc32/crc32c_x86.cc
Labels: MariaDB Corporation
