Repository MariaDB/server, pull requests merged in 2025-07, with the labels that each got.

#4125 MDEV-23699 Assertion failed in ha_tina::delete_row
  mysql-test/main/repair.result
  mysql-test/main/repair.test
  storage/csv/ha_tina.cc
Labels: MariaDB Corporation

#4075 MDEV-29474 - main.lock_sync fails with timeout
  mysql-test/main/lock_sync.result
  mysql-test/main/lock_sync.test
  mysql-test/main/mdl_sync.result
  mysql-test/main/mdl_sync.test
  sql/mdl.cc
Labels: MariaDB Foundation

#4093 MDEV-37107 - Optimise dot_product by loop-unrolling by a factor of 4
  sql/vector_mhnsw.cc
Labels: External Contribution

#4159 MDEV-37123 dict_table_open_on_id() fails to release dict_sys.latch
  mysql-test/suite/innodb/r/innodb_defrag_stats.result
  mysql-test/suite/innodb/t/innodb_defrag_stats.test
  storage/innobase/dict/dict0dict.cc
Labels: MariaDB Corporation

#4129 MDEV-37048 revert MSAN my_vsnprintf_ex for double workaround
  strings/my_vsnprintf.c
Labels: MariaDB Foundation

#4164 MDEV-37143 mariabackup fails with "self-signed certificate" on Windows
  mysql-test/suite/mariabackup/backup_ssl.result
  mysql-test/suite/mariabackup/backup_ssl.test
  sql-common/client.c
Labels: MariaDB Corporation

#2651 MDEV-35826 Fix COLUMNSTORE in Debian CI builds
  debian/control
Labels: MariaDB Foundation

#4135 MDEV-37052 JSON_SCHEMA_VALID stack overflow handling errors
  sql/item_jsonfunc.cc
  sql/json_schema.cc
  sql/json_table.cc
  sql/sql_parse.h
Labels: MariaDB Foundation

#4081 Fix building with gcc 16 (evex512 removal)
  mysys/crc32/crc32c_x86.cc
Labels: External Contribution

#4151 MDEV-37092 galera_new_cluster installed under WITH_WSREP=OFF
  cmake/systemd.cmake
  scripts/CMakeLists.txt
Labels: MariaDB Foundation

#4170 MDEV-37170 Enable AVX10.1 CRC-32 on GCC 16
  mysys/crc32/crc32c_x86.cc
Labels: MariaDB Corporation

#4175 fix incorrect merge 15700f54c212 (part 2) rocksdb_rpl.rpl_xa
  storage/rocksdb/mysql-test/rocksdb_rpl/r/rpl_xa.result
Labels: MariaDB Foundation

#4161 MDEV-37117 Assertion `!thd->transaction->xid_state.is_explicit_XA() |…
  mysql-test/main/xa.result
  mysql-test/main/xa.test
  mysql-test/suite/innodb/r/trx_deadlock.result
  mysql-test/suite/innodb/t/trx_deadlock.test
  sql/sql_parse.cc
Labels: MariaDB Corporation

#4183 MDEV-37169: MSAN disable main.{mysqladmin,statistics_upgrade_not_done}
  mysql-test/main/mysqladmin.test
  mysql-test/main/statistics_upgrade_not_done.test
Labels: MariaDB Foundation

#4181 MDEV-37183 Scrubbing empty record breaks recovery
  mysql-test/suite/innodb/r/scrub_debug.result
  mysql-test/suite/innodb/t/scrub_debug.test
  storage/innobase/page/page0page.cc
Labels: MariaDB Corporation

#4126 MDEV-35913 Assertion `m_comparator.cmp_type() != ROW_RESULT' in Item_…
  mysql-test/main/type_row.result
  mysql-test/main/type_row.test
  sql/opt_vcol_substitution.cc
Labels: MariaDB Corporation

#4176 MDEV-37044 derived_wth_keys optimization not applied where it should
  mysql-test/main/derived.result
  mysql-test/main/derived.test
  mysql-test/main/derived_view.result
  sql/table.cc
Labels: MariaDB Corporation

#4019 MDEV-36092 New-style hint: [NO_]SPLIT_MATERIALIZED
  mysql-test/main/opt_hints_split_materialized.result
  mysql-test/main/opt_hints_split_materialized.test
  sql/opt_hints.cc
  sql/opt_hints.h
  sql/opt_hints_parser.cc
  sql/opt_hints_parser.h
  sql/opt_split.cc
  sql/table.h
Labels: MariaDB Corporation

#4200 Sort output of `binlog_mysqlbinlog_warn_stop_gtid`
  mysql-test/suite/binlog/t/binlog_mysqlbinlog_warn_stop_position.inc
Labels: MariaDB Corporation, Replication

#4203 MDEV-37103 innodb_immediate_scrub_data_uncompressed=ON may break innodb_undo_log_truncate=ON
  storage/innobase/buf/buf0flu.cc
  storage/innobase/fil/fil0fil.cc
Labels: MariaDB Corporation

#4208 MDEV-37250 buf_pool_t::shrink() assertion failure
  mysql-test/suite/innodb/r/innodb_buffer_pool_shrink_temporary.result
  mysql-test/suite/innodb/t/innodb_buffer_pool_shrink_temporary.opt
  mysql-test/suite/innodb/t/innodb_buffer_pool_shrink_temporary.test
  storage/innobase/buf/buf0buf.cc
Labels: MariaDB Corporation

#4212 MDEV-37263 Hang or crash when shrinking innodb_buffer_pool_size
  mysql-test/suite/innodb/r/innodb_buffer_pool_shrink.result
  mysql-test/suite/innodb/t/innodb_buffer_pool_shrink.test
  storage/innobase/buf/buf0buf.cc
Labels: MariaDB Corporation

#4202 MDEV-36839: Revert MDEV-7409
  cmake/wsrep.cmake
  config.h.cmake
  mysql-test/suite/rpl/r/rpl_rbr_monitor.result
  mysql-test/suite/rpl/t/rpl_rbr_monitor.test
  sql/log_event_server.cc
  sql/sql_class.cc
  sql/sql_class.h
Labels: MariaDB Corporation, Replication

#4174 MDEV-36906: RBR crashes upon DML after CONVERT PARTITION
  mysql-test/suite/rpl/r/rpl_alter_convert_partition.result
  mysql-test/suite/rpl/t/rpl_alter_convert_partition.test
  sql/sql_partition.cc
  sql/sql_table.cc
  sql/sql_table.h
Labels: MariaDB Corporation, Replication

#4190 MDEV-30711: Crash in add_keyuses_for_splitting() when joining with a …
  mysql-test/main/derived_split_innodb.result
  mysql-test/main/derived_split_innodb.test
  sql/item.h
  sql/opt_split.cc
Labels: MariaDB Corporation

#3909 MDEV-35635: START SLAVE UNTIL allows CHANGE MASTER TO options
  mysql-test/main/start_slave_until.result
  mysql-test/main/start_slave_until.test
  sql/sql_yacc.yy
Labels: External Contribution, Replication

#4199 MDEV-37083: Fix type mismatch in sys views
  mysql-test/suite/encryption/r/innochecksum.result
  mysql-test/suite/encryption/t/innochecksum.opt
  mysql-test/suite/encryption/t/innochecksum.test
  mysql-test/suite/sysschema/r/v_innodb_buffer_stats_by_schema.result
  mysql-test/suite/sysschema/r/v_innodb_buffer_stats_by_table.result
  mysql-test/suite/sysschema/t/v_innodb_buffer_stats_by_schema.test
  mysql-test/suite/sysschema/t/v_innodb_buffer_stats_by_table.test
  scripts/sys_schema/views/i_s/innodb_buffer_stats_by_schema.sql
  scripts/sys_schema/views/i_s/innodb_buffer_stats_by_table.sql
  scripts/sys_schema/views/i_s/x_innodb_buffer_stats_by_table.sql
Labels: MariaDB Corporation

#4219 MDEV-37308 main.failed_auth_unixsocket fails
  mysql-test/main/failed_auth_unixsocket.result
  mysql-test/main/failed_auth_unixsocket.test
Labels: MariaDB Corporation

#4224 MDEV-36385 Fix slave_parallel_threads_basic test in view-protocol mode
  mysql-test/suite/sys_vars/r/slave_parallel_threads_basic.result
  mysql-test/suite/sys_vars/t/slave_parallel_threads_basic.test
Labels: External Contribution
